const ROLES = Object.freeze({
  ADMIN: 'ADMIN',
  CUSTOMER: 'CUSTOMER',
});

const APPLICATION_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
});

const ORDER_STATUS = Object.freeze({
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
});

const PAYMENT_STATUS = Object.freeze({
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
});

const PAYMENT_METHOD = Object.freeze({
  CREDIT_CARD: 'CREDIT_CARD',
  DEBIT_CARD: 'DEBIT_CARD',
  NET_BANKING: 'NET_BANKING',
  UPI: 'UPI',
  WALLET: 'WALLET',
});

const PAYMENT_TRANSACTION_STATUS = Object.freeze({
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
});

const POLICY_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED',
  CLAIMED: 'CLAIMED',
});

const CLAIM_STATUS = Object.freeze({
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  SETTLED: 'SETTLED',
});

const PREMIUM_FREQUENCY = Object.freeze({
  MONTHLY: 'MONTHLY',
  QUARTERLY: 'QUARTERLY',
  HALF_YEARLY: 'HALF_YEARLY',
  YEARLY: 'YEARLY',
});

const FIELD_TYPES = Object.freeze({
  TEXT: 'TEXT',
  NUMBER: 'NUMBER',
  EMAIL: 'EMAIL',
  DATE: 'DATE',
  SELECT: 'SELECT',
  RADIO: 'RADIO',
  CHECKBOX: 'CHECKBOX',
  TEXTAREA: 'TEXTAREA',
  FILE: 'FILE',
});

const AUDIT_ACTIONS = Object.freeze({
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  STATUS_CHANGE: 'STATUS_CHANGE',
});

const DOCUMENT_TYPES = Object.freeze({
  MEDICAL_REPORT: 'MEDICAL_REPORT',
  POLICE_REPORT: 'POLICE_REPORT',
  ID_PROOF: 'ID_PROOF',
  ADDRESS_PROOF: 'ADDRESS_PROOF',
  INCOME_PROOF: 'INCOME_PROOF',
  CLAIM_FORM: 'CLAIM_FORM',
  PHOTO: 'PHOTO',
  OTHER: 'OTHER',
});

const FILE_TYPES = Object.freeze({
  IMAGE: 'IMAGE',
  VIDEO: 'VIDEO',
  DOCUMENT: 'DOCUMENT',
});

const LOGIN_STATUS = Object.freeze({
  SUCCESS: 'Success',
  FAILED: 'Failed',
});

const DISPLAY_ROLES = Object.freeze({
  ADMIN: 'ADMIN',
  CUSTOMER: 'USER',
});

module.exports = {
  ROLES,
  APPLICATION_STATUS,
  ORDER_STATUS,
  PAYMENT_STATUS,
  PAYMENT_METHOD,
  PAYMENT_TRANSACTION_STATUS,
  POLICY_STATUS,
  CLAIM_STATUS,
  PREMIUM_FREQUENCY,
  FIELD_TYPES,
  AUDIT_ACTIONS,
  DOCUMENT_TYPES,
  FILE_TYPES,
  LOGIN_STATUS,
  DISPLAY_ROLES,
};
